server:
  port: 8080

spring:
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 最大支持文件大小
      max-file-size: 1024MB
      # 最大支持请求大小
      max-request-size: 1024MB